### PR TITLE
Rewrite Codebase

### PR DESCRIPTION
**Pull request by dbwww**
Here it is

### CODE REVIEW

**Comment by dbwww** [comment]
not sure why but the exe is marked as virus... will try to fix with update

**Comment by lerichardson** [comment]
No worries about that, it costs money that I don't have... Kinda like apple and the app store

**Comment by dbwww** [comment]
whats going on with the review- anything wrong, or that needs changing?

**Review by lerichardson — APPROVED** [review]

**Comment by lerichardson** [comment]
Can I get the raw exefile?

**Review by lerichardson — CHANGES_REQUESTED** [review]
I would suggest changing the "Save", "Save As", and "Open file" Colors to #00000 or rgb(0, 0, 0) so they don't look grayed out.

**Comment by dbwww** [comment]
I will when I get home from school.

**Comment by dbwww** [comment]
added more commits!

**Comment by lerichardson** [comment]
LGTM

**Pull request merged**
