### PR TITLE
New UI design, easier to read and shorter code.

### PR DESCRIPTION
**Pull request by dbwww**
More "modern" UI design.  Not exactly a fan of those, but I think it is easier on the eyes

### CODE REVIEW

**Review by lerichardson — CHANGES_REQUESTED** [review]
4 things: maybe make the file button a little smaller (I can do that after commit, if you'd like) and change the hover color to something that doesn't match the text, and third, add a "help" button in the top bar that has a link to `https://lerichardson.github.io/clack/help/home`. Finally, maybe make a Control-S hotkey to save.

**Comment by darthbananawww** [comment]
hey, this is my account i use at school btw.  I will fix these when i get home

**Comment by dbwww** [comment]
im gonna be honest i completely forgot about this so i will fix it now

**Comment by dbwww** [comment]
yeah the project won't even start so idk what to do

**Pull request closed without merging**
